-- MySQL Script generated by MySQL Workbench
-- mar 18 nov 2014 18:32:11 PET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema openack
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `openack` ;

-- -----------------------------------------------------
-- Schema openack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openack` DEFAULT CHARACTER SET latin1 ;
USE `openack` ;

-- -----------------------------------------------------
-- Table `openack`.`Universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Universidad` (
  `idUniversidad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `NumeroDeAportes` INT NULL,
  PRIMARY KEY (`idUniversidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openack`.`BolsaDeTrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`BolsaDeTrabajo` (
  `idBolsaDeTrabajo` INT NOT NULL AUTO_INCREMENT,
  `ListaDeEmpresas` VARCHAR(45) NULL,
  `Rubro` VARCHAR(45) NULL,
  `Requerimientos` VARCHAR(45) NULL,
  `Puntuacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idBolsaDeTrabajo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openack`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Rubro` VARCHAR(45) NULL,
  `Puntuacion` INT NULL,
  `Comentarios` VARCHAR(45) NULL,
  `BolsaDeTrabajo_idBolsaDeTrabajo` INT NOT NULL,
  PRIMARY KEY (`idEmpresa`, `BolsaDeTrabajo_idBolsaDeTrabajo`),
  CONSTRAINT `fk_Empresa_BolsaDeTrabajo1`
    FOREIGN KEY (`BolsaDeTrabajo_idBolsaDeTrabajo`)
    REFERENCES `openack`.`BolsaDeTrabajo` (`idBolsaDeTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empresa_BolsaDeTrabajo1_idx` ON `openack`.`Empresa` (`BolsaDeTrabajo_idBolsaDeTrabajo` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Puntuacion` INT NULL,
  `NivelEducativo` VARCHAR(45) NOT NULL,
  `Carrera` VARCHAR(45) NULL,
  `Universidad_idUniversidad` INT NULL,
  `Empresa_idEmpresa` INT NULL,
  `Empresa_BolsaDeTrabajo_idBolsaDeTrabajo` INT NULL,
  PRIMARY KEY (`idUsuario`, `Universidad_idUniversidad`, `Empresa_idEmpresa`, `Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`),
  CONSTRAINT `fk_Usuario_Universidad1`
    FOREIGN KEY (`Universidad_idUniversidad`)
    REFERENCES `openack`.`Universidad` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa` , `Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`)
    REFERENCES `openack`.`Empresa` (`idEmpresa` , `BolsaDeTrabajo_idBolsaDeTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Universidad1_idx` ON `openack`.`Usuario` (`Universidad_idUniversidad` ASC);

CREATE INDEX `fk_Usuario_Empresa1_idx` ON `openack`.`Usuario` (`Empresa_idEmpresa` ASC, `Empresa_BolsaDeTrabajo_idBolsaDeTrabajo` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Facultad` (
  `idFacultad` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `NumeroDeAportes` INT NULL,
  `Universidad_idUniversidad` INT NOT NULL,
  PRIMARY KEY (`idFacultad`, `Universidad_idUniversidad`),
  CONSTRAINT `fk_Facultad_Universidad1`
    FOREIGN KEY (`Universidad_idUniversidad`)
    REFERENCES `openack`.`Universidad` (`idUniversidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Facultad_Universidad1_idx` ON `openack`.`Facultad` (`Universidad_idUniversidad` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Comentarios` VARCHAR(45) NULL,
  `MallaCurricular` VARCHAR(45) NULL,
  `Facultad_idFacultad` INT NOT NULL,
  PRIMARY KEY (`idCarrera`, `Facultad_idFacultad`),
  CONSTRAINT `fk_Carrera_Facultad1`
    FOREIGN KEY (`Facultad_idFacultad`)
    REFERENCES `openack`.`Facultad` (`idFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Carrera_Facultad1_idx` ON `openack`.`Carrera` (`Facultad_idFacultad` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Puntuacion` VARCHAR(45) NULL,
  `Sylabus` VARCHAR(45) NULL,
  `Aportes` VARCHAR(45) NULL,
  `Carrera_idCarrera` INT NOT NULL,
  `Carrera_Facultad_idFacultad` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `Carrera_idCarrera`, `Carrera_Facultad_idFacultad`),
  CONSTRAINT `fk_Curso_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera` , `Carrera_Facultad_idFacultad`)
    REFERENCES `openack`.`Carrera` (`idCarrera` , `Facultad_idFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Curso_Carrera1_idx` ON `openack`.`Curso` (`Carrera_idCarrera` ASC, `Carrera_Facultad_idFacultad` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Tema` (
  `idTema` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `NumeroDeAportes` INT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idTema`, `Curso_idCurso`),
  CONSTRAINT `fk_Tema_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `openack`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tema_Curso1_idx` ON `openack`.`Tema` (`Curso_idCurso` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Aporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Aporte` (
  `idAporte` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `tipoDeAporte` VARCHAR(45) NULL,
  `Puntuacion` INT NULL,
  `Comentarios` VARCHAR(45) NULL,
  `Tema_idTema` INT NOT NULL,
  `Tema_Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idAporte`, `Tema_idTema`, `Tema_Curso_idCurso`),
  CONSTRAINT `fk_Aporte_Tema1`
    FOREIGN KEY (`Tema_idTema` , `Tema_Curso_idCurso`)
    REFERENCES `openack`.`Tema` (`idTema` , `Curso_idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Aporte_Tema1_idx` ON `openack`.`Aporte` (`Tema_idTema` ASC, `Tema_Curso_idCurso` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Texto` VARCHAR(45) NULL,
  `Puntuacion` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Universidad_idUniversidad` INT NOT NULL,
  `Usuario_Empresa_idEmpresa` INT NOT NULL,
  `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo` INT NOT NULL,
  PRIMARY KEY (`idComentario`, `Usuario_idUsuario`, `Usuario_Universidad_idUniversidad`, `Usuario_Empresa_idEmpresa`, `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`),
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Universidad_idUniversidad` , `Usuario_Empresa_idEmpresa` , `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`)
    REFERENCES `openack`.`Usuario` (`idUsuario` , `Universidad_idUniversidad` , `Empresa_idEmpresa` , `Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Comentario_Usuario1_idx` ON `openack`.`Comentario` (`Usuario_idUsuario` ASC, `Usuario_Universidad_idUniversidad` ASC, `Usuario_Empresa_idEmpresa` ASC, `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Ciclo` (
  `idCiclo` INT NOT NULL AUTO_INCREMENT,
  `NumeroDeCiclo` INT NOT NULL,
  PRIMARY KEY (`idCiclo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openack`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Historial` (
  `idHistorial` INT NOT NULL AUTO_INCREMENT,
  `NumeroDeAportes` INT NULL,
  `Aportes` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Universidad_idUniversidad` INT NOT NULL,
  `Usuario_Empresa_idEmpresa` INT NOT NULL,
  `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo` INT NOT NULL,
  PRIMARY KEY (`idHistorial`, `Usuario_idUsuario`, `Usuario_Universidad_idUniversidad`, `Usuario_Empresa_idEmpresa`, `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`),
  CONSTRAINT `fk_Historial_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Universidad_idUniversidad` , `Usuario_Empresa_idEmpresa` , `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`)
    REFERENCES `openack`.`Usuario` (`idUsuario` , `Universidad_idUniversidad` , `Empresa_idEmpresa` , `Empresa_BolsaDeTrabajo_idBolsaDeTrabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Historial_Usuario1_idx` ON `openack`.`Historial` (`Usuario_idUsuario` ASC, `Usuario_Universidad_idUniversidad` ASC, `Usuario_Empresa_idEmpresa` ASC, `Usuario_Empresa_BolsaDeTrabajo_idBolsaDeTrabajo` ASC);


-- -----------------------------------------------------
-- Table `openack`.`Carrera_has_Ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openack`.`Carrera_has_Ciclo` (
  `Carrera_idCarrera` INT NOT NULL,
  `Carrera_Facultad_idFacultad` INT NOT NULL,
  `Ciclo_idCiclo` INT NOT NULL,
  PRIMARY KEY (`Carrera_idCarrera`, `Carrera_Facultad_idFacultad`, `Ciclo_idCiclo`),
  CONSTRAINT `fk_Carrera_has_Ciclo_Carrera1`
    FOREIGN KEY (`Carrera_idCarrera` , `Carrera_Facultad_idFacultad`)
    REFERENCES `openack`.`Carrera` (`idCarrera` , `Facultad_idFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrera_has_Ciclo_Ciclo1`
    FOREIGN KEY (`Ciclo_idCiclo`)
    REFERENCES `openack`.`Ciclo` (`idCiclo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Carrera_has_Ciclo_Ciclo1_idx` ON `openack`.`Carrera_has_Ciclo` (`Ciclo_idCiclo` ASC);

CREATE INDEX `fk_Carrera_has_Ciclo_Carrera1_idx` ON `openack`.`Carrera_has_Ciclo` (`Carrera_idCarrera` ASC, `Carrera_Facultad_idFacultad` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
